package oodj_ass;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class AdminDashboard extends javax.swing.JFrame {
    private final UserManager userManager;
    private DefaultTableModel model;
//    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());
    private final User currentUser;

    public AdminDashboard(User user) {
        initComponents();
        this.currentUser = user;
        
        this.userManager = new UserManager();
        initTable();
        loadTableData(""); 
        
        if (!currentUser.getRole().equalsIgnoreCase("ADMIN")) {

            btnAdd.setVisible(false);
            btnUpdate.setVisible(false);
            btnDeactivate.setVisible(false);
            btnReactivate.setVisible(false); 

            txtUsername.setEditable(false);
            txtPassword.setEditable(false);
            txtName.setEditable(false);
            txtEmail.setEditable(false);
            cmbRole.setEnabled(false);

            this.setTitle("User Directory (Search Only Mode)");
        }
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    private void initTable() {
        model = (DefaultTableModel) tblUsers.getModel();
        model.setColumnIdentifiers(new Object[]{"ID", "Username", "Name", "Role", "Active"});
    }
    
    private void loadTableData(String query) {
        model.setRowCount(0); // Clear table
        List<User> users = userManager.getAllUsers();
        
        for (User u : users) {
            boolean matches = query.isEmpty() || 
                              u.getUsername().toLowerCase().contains(query.toLowerCase()) ||
                              u.getUserId().toLowerCase().contains(query.toLowerCase()) ||
                              u.getFullName().toLowerCase().contains(query.toLowerCase());
            
            if (matches) {
                model.addRow(new Object[]{
                    u.getUserId(), u.getUsername(), u.getFullName(), 
                    u.getEmail(), u.getRole(), u.isActive()
                });
            }
        }
    }
    
    
    private void clearFields() {
        txtUsername.setText("");
        txtPassword.setText("");
        txtName.setText("");
        txtEmail.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        cmbRole = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReactivate = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1160, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1160, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 700));

        tblUsers.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Name", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        cmbRole.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick Role", "Admin", "Academic Officer", " " }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAdd.setText("Add user");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDeactivate.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnDeactivate.setText("Deactivate");
        btnDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setText("E-mail");

        btnReactivate.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnReactivate.setText("Reactivate");
        btnReactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactivateActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnSearch.setText("Search:");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setText("Role");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(8, 8, 8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(btnAdd)
                .addGap(146, 146, 146)
                .addComponent(btnUpdate)
                .addGap(142, 142, 142)
                .addComponent(btnDeactivate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnReactivate)
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(65, 65, 65)))
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDeactivate)
                    .addComponent(btnReactivate))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String user = txtUsername.getText().trim();
        String pass = txtPassword.getText().trim();
        String name = txtName.getText().trim();
        String email = txtEmail.getText().trim();
        String role = (String) cmbRole.getSelectedItem();

        if(user.isEmpty() || pass.isEmpty() || name.isEmpty() || email.isEmpty() || role.equals("Pick Role")) {
            if (role.equals("Pick Role")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a valid Role (Admin or Academic Officer).");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            }
            return; 
        }

        if (!isValidEmail(email)) {
             javax.swing.JOptionPane.showMessageDialog(this, "Invalid Email Format! (e.g., name@email.com)");
             return;
        }

        for (User u : userManager.getAllUsers()) {
            if (u.getUsername().equalsIgnoreCase(user)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Username already exists!");
                return;
            }
            if (u.getEmail().equalsIgnoreCase(email)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Email is already used!");
                return;
            }
        }

        String newID = generateNextUserId(role);
        User newUser;
        
        if(role.equals("Admin")) {
            newUser = new Admin(newID, user, pass, name, email, true);
        } else {
            newUser = new AcademicOfficer(newID, user, pass, name, email, true);
        }

        userManager.getAllUsers().add(newUser);
        userManager.saveUsersToFile();
        loadTableData("");
        
        javax.swing.JOptionPane.showMessageDialog(this, "User Added! ID: " + newID);
        clearFields();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow == -1) return;
        
        String username = (String) model.getValueAt(selectedRow, 1);
        User userToBan = userManager.findByUsername(username);


        if (userToBan != null) {
            userToBan.setActive(false); // Deactivate
            userManager.saveUsersToFile(); // Save changes to file
            loadTableData(""); // Refresh UI
            JOptionPane.showMessageDialog(this, "User Deactivated.");
        }
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a user to update.");
            return;
        }

        String currentUsername = (String) model.getValueAt(selectedRow, 1);
        User userToUpdate = userManager.findByUsername(currentUsername);

        if (userToUpdate != null) {
            String newName = txtName.getText().trim();
            String newEmail = txtEmail.getText().trim();
            String newPass = txtPassword.getText().trim();
            String selectedRoleString = (String) cmbRole.getSelectedItem(); 

            if (!newEmail.isEmpty()) {
                if (!isValidEmail(newEmail)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid Email Format!");
                    return;
                }
                for (User u : userManager.getAllUsers()) {
                    if (u.getEmail().equalsIgnoreCase(newEmail) && !u.getUsername().equals(currentUsername)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Email belongs to another account.");
                        return;
                    }
                }
                userToUpdate.setEmail(newEmail);
            }

            if(!newName.isEmpty()) userToUpdate.setFullName(newName);
            if(!newPass.isEmpty()) userToUpdate.setPassword(newPass);

            if (selectedRoleString != null && !selectedRoleString.equals("Pick Role")) {
                
                String targetRole = selectedRoleString.equalsIgnoreCase("Admin") ? "ADMIN" : "ACADEMIC_OFFICER";
                
                if (!userToUpdate.getRole().equalsIgnoreCase(targetRole)) {
                    
                    String newId = generateNextUserId(selectedRoleString);
                    
                    userToUpdate.setRole(targetRole);
                    userToUpdate.setUserId(newId); 
                    
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Role changed to " + selectedRoleString + ".\n" +
                        "User ID automatically updated to: " + newId);
                }
            }

            userManager.saveUsersToFile();
            loadTableData(""); 
            javax.swing.JOptionPane.showMessageDialog(this, "User details updated successfully!");
            clearFields();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnReactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactivateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow == -1) return;

        String username = (String) model.getValueAt(selectedRow, 1);
        User userToActivate = userManager.findByUsername(username);

        if (userToActivate != null) {
            userToActivate.setActive(true); 
            userManager.saveUsersToFile();
            loadTableData("");
            JOptionPane.showMessageDialog(this, "User Reactivated!");
        }
    }//GEN-LAST:event_btnReactivateActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String query = txtSearch.getText().trim();
        loadTableData(query);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private String generateNextUserId(String role) {
        String prefix;
        if (role.equalsIgnoreCase("Admin")) {
            prefix = "ADM";
        } else {
            prefix = "AO";
        }
        
        int maxId = 0;
        
        for (User u : userManager.getAllUsers()) {
            if (u.getUserId().startsWith(prefix)) {
                try {
                    int numericPart = Integer.parseInt(u.getUserId().substring(prefix.length()));
                    if (numericPart > maxId) maxId = numericPart;
                } catch (NumberFormatException e) {
                }
            }
        }

        return String.format("%s%03d", prefix, maxId + 1);
    }

    private boolean isValidEmail(String email) {
        return email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnReactivate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
