/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_ass;

/**
 *
 * @author User
 */
public class ARP_UI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ARP_UI.class.getName());

    /**
     * Creates new form ARP_UI
     */
    public ARP_UI() {
        initComponents();
        
        // Set header font
        arp_tabel1.getTableHeader().setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 20));

        // Center header text
        javax.swing.table.DefaultTableCellRenderer headerRenderer = 
                (javax.swing.table.DefaultTableCellRenderer) arp_tabel1.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jButtonUserManagement = new javax.swing.JButton();
        jButtonEligibility = new javax.swing.JButton();
        jButtonRecovery = new javax.swing.JButton();
        jButtonAPR = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        apr_titile = new javax.swing.JLabel();
        sid_search = new javax.swing.JTextField();
        arp_sid = new javax.swing.JLabel();
        arp_search = new javax.swing.JButton();
        arp_sid1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        arp_tabel1 = new javax.swing.JTable();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Academic Performance Report");
        setMaximumSize(new java.awt.Dimension(1160, 700));
        setMinimumSize(new java.awt.Dimension(1160, 700));
        setPreferredSize(new java.awt.Dimension(1160, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(183, 201, 197));
        jPanel1.setMaximumSize(new java.awt.Dimension(1160, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1160, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setBackground(new java.awt.Color(95, 106, 105));

        jButtonUserManagement.setBackground(new java.awt.Color(95, 106, 105));
        jButtonUserManagement.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUserManagement.setText("User Management");
        jButtonUserManagement.setToolTipText("");
        jButtonUserManagement.setBorderPainted(false);
        jButtonUserManagement.setContentAreaFilled(false);
        jButtonUserManagement.setFocusPainted(false);
        jButtonUserManagement.setOpaque(true);
        jButtonUserManagement.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserManagementActionPerformed(evt);
            }
        });

        jButtonEligibility.setBackground(new java.awt.Color(95, 106, 105));
        jButtonEligibility.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonEligibility.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEligibility.setText("<html><center>Eligibility Check<br>and Enrolment</center></html> ");
        jButtonEligibility.setToolTipText("");
        jButtonEligibility.setBorderPainted(false);
        jButtonEligibility.setContentAreaFilled(false);
        jButtonEligibility.setFocusPainted(false);
        jButtonEligibility.setOpaque(true);
        jButtonEligibility.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonEligibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEligibilityActionPerformed(evt);
            }
        });

        jButtonRecovery.setBackground(new java.awt.Color(95, 106, 105));
        jButtonRecovery.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonRecovery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecovery.setText("Course Recovery Plan");
        jButtonRecovery.setToolTipText("");
        jButtonRecovery.setBorderPainted(false);
        jButtonRecovery.setContentAreaFilled(false);
        jButtonRecovery.setFocusPainted(false);
        jButtonRecovery.setOpaque(true);
        jButtonRecovery.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecoveryActionPerformed(evt);
            }
        });

        jButtonAPR.setBackground(new java.awt.Color(95, 106, 105));
        jButtonAPR.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonAPR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAPR.setText("<html><center>Academic<br>Performance Report</center></html> ");
        jButtonAPR.setBorderPainted(false);
        jButtonAPR.setContentAreaFilled(false);
        jButtonAPR.setFocusPainted(false);
        jButtonAPR.setOpaque(true);
        jButtonAPR.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonAPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAPRActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        logout.setText("Log Out");
        logout.setBorderPainted(false);
        logout.setFocusPainted(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEligibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jButtonUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEligibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(62, 62, 62))
        );

        jPanel1.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 700));

        apr_titile.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        apr_titile.setText("Academic Performance Report");
        apr_titile.setToolTipText("");
        jPanel1.add(apr_titile, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        sid_search.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        sid_search.setMaximumSize(new java.awt.Dimension(100, 30));
        sid_search.setMinimumSize(new java.awt.Dimension(100, 30));
        sid_search.setPreferredSize(new java.awt.Dimension(100, 30));
        sid_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sid_searchActionPerformed(evt);
            }
        });
        jPanel1.add(sid_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        arp_sid.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        arp_sid.setText("Intake:");
        jPanel1.add(arp_sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        arp_search.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        arp_search.setLabel("Search");
        arp_search.setOpaque(true);
        arp_search.setPreferredSize(new java.awt.Dimension(70, 30));
        arp_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arp_searchActionPerformed(evt);
            }
        });
        jPanel1.add(arp_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        arp_sid1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        arp_sid1.setText("Student ID:");
        arp_sid1.setMaximumSize(new java.awt.Dimension(86, 30));
        arp_sid1.setMinimumSize(new java.awt.Dimension(86, 30));
        arp_sid1.setPreferredSize(new java.awt.Dimension(86, 30));
        jPanel1.add(arp_sid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(100, 30));
        jComboBox1.setMinimumSize(new java.awt.Dimension(100, 30));
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        arp_tabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        arp_tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester", "Course ID", "Course Name", "Credit Hours", "Grade", "GPA"
            }
        ));
        arp_tabel1.setRowHeight(35);
        arp_tabel1.setShowGrid(false);
        jScrollPane1.setViewportView(arp_tabel1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 870, 230));

        title.setBackground(new java.awt.Color(157, 208, 153));
        title.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        title.setText("Eligibility Check and Enrolment");
        title.setToolTipText("");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(title)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(title)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserManagementActionPerformed

    private void jButtonEligibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEligibilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEligibilityActionPerformed

    private void jButtonRecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecoveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRecoveryActionPerformed

    private void jButtonAPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAPRActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void arp_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arp_searchActionPerformed

    }//GEN-LAST:event_arp_searchActionPerformed

    private void sid_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sid_searchActionPerformed
        sid_searchActionPerformed(evt); //when keyin the sid and press enter also can search
    }//GEN-LAST:event_sid_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ARP_UI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apr_titile;
    private javax.swing.JButton arp_search;
    private javax.swing.JLabel arp_sid;
    private javax.swing.JLabel arp_sid1;
    private javax.swing.JTable arp_tabel1;
    private javax.swing.JPanel dashboard;
    private javax.swing.JButton jButtonAPR;
    private javax.swing.JButton jButtonEligibility;
    private javax.swing.JButton jButtonRecovery;
    private javax.swing.JButton jButtonUserManagement;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField sid_search;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
