package oodj_ass;

/**
 *
 * @author User
 */

import java.util.ArrayList;
import java.io.*;



public class ECE_UI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ECE_UI.class.getName());

    /**
     * Creates new form ECE_UI
     */
   
    // Load CSV file
    public ArrayList<String[]> loadFile(String filename) {
        ArrayList<String[]> list = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("data/" + filename))) {
            String line;
            br.readLine(); // skip header
            while ((line = br.readLine()) != null) {
                list.add(line.split(","));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return list;
    }

    
    private void updateTable(ArrayList<String[]> data) {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

        model.setRowCount(0); // clear table

        for (String[] row : data) {
            model.addRow(new Object[]{
                row[0],   // Student ID
                row[1],   // Semester
                row[2],   // CGPA
                row[3],   // Eligibility
                "View"    // Button label
            });
        }
    }
    
    
    private void showDetails(String studentID, String semester) {
        ArrayList<String[]> grades = loadFile("grades.txt");
        ArrayList<String[]> courses = loadFile("courses.txt");

        StringBuilder sb = new StringBuilder();
        sb.append("===== Student: ").append(studentID)
          .append(" (").append(semester).append(") =====\n");

        double totalGP = 0;
        int totalCH = 0;
        int failCount = 0;

        for (String[] g : grades) {
            if (!g[0].equals(studentID)) continue;
            if (!g[2].equals(semester)) continue;

            String courseID = g[1];
            String grade = g[5];
            double gpa = Double.parseDouble(g[6]);

            String[] c = null;
            for (String[] x : courses) {
                if (x[0].equals(courseID)) c = x;
            }

            int credit = Integer.parseInt(c[2]);
            double gp = gpa * credit;

            totalGP += gp;
            totalCH += credit;
            if (gpa < 2.0) failCount++;

            sb.append(courseID)
              .append(" | Grade: ").append(grade)
              .append(" (").append(String.format("%.2f", gpa))
              .append(") * ").append(credit)
              .append(" credits = ").append(String.format("%.2f", gp))
              .append("\n");
        }

        double cgpa = totalGP / totalCH;
        sb.append("Total Grade Points = ").append(totalGP).append("\n");
        sb.append("Total Credit Hours = ").append(totalCH).append("\n");
        sb.append("Total Fails = ").append(failCount).append("\n");
        sb.append("CGPA = ").append(String.format("%.2f", cgpa)).append("\n");
        sb.append("Eligible Next Year: ").append(cgpa >= 2.0 && failCount <= 3 ? "YES" : "NO");

        javax.swing.JOptionPane.showMessageDialog(this, sb.toString());
    }


    public ECE_UI() {
        initComponents();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                int col = jTable1.columnAtPoint(evt.getPoint());

                if (col == 4) { // Details column
                    String sid = jTable1.getValueAt(row, 0).toString();
                    String sem = jTable1.getValueAt(row, 1).toString();
                    showDetails(sid, sem);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eligibility Checker");
        setMaximumSize(new java.awt.Dimension(950, 700));
        setMinimumSize(new java.awt.Dimension(950, 700));
        setPreferredSize(new java.awt.Dimension(950, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.setText("Enter Student ID");
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField1.setRequestFocusEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        jButton1.setText("🔍 ");
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Eligible", "No Eligible" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(180, 30));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Eligibility Checker");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Semester", "CGPA", "Eligibility", "Details"
            }
        ));
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 900, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(950, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String selected = jComboBox1.getSelectedItem().toString();
        ArrayList<String[]> resultList = loadFile("result.txt");
        ArrayList<String[]> filtered = new ArrayList<>();

        for (String[] r : resultList) {
            if (selected.equals("All")) {
                filtered.add(r);
            } 
            else if (selected.equals("Eligible") && r[3].equals("YES")) {
                filtered.add(r);
            } 
            else if (selected.equals("No Eligible") && r[3].equals("NO")) {
                filtered.add(r);
            }
        }

        updateTable(filtered);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String searchID = jTextField1.getText().trim();
        if (searchID.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter a Student ID!");
            return;
        }

        ArrayList<String[]> resultList = loadFile("result.txt");
        ArrayList<String[]> matched = new ArrayList<>();

        for (String[] r : resultList) {
            if (r[0].equalsIgnoreCase(searchID)) {
                matched.add(r);
            }
        }

        if (matched.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
        }

        updateTable(matched);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ECE_UI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
