/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_ass;

/**
 *
 * @author User
 */

import java.util.ArrayList;
import java.io.*;
import java.awt.Color;

public class ECE_UI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ECE_UI.class.getName());

    /**
     * Creates new form ECE_UI
     */
   
    // Load CSV file
    public ArrayList<String[]> loadFile(String filename) {
        ArrayList<String[]> list = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("data/" + filename))) {
            String line;
            br.readLine(); // skip header
            while ((line = br.readLine()) != null) {
                list.add(line.split(","));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return list;
    }

    
    private void updateTable(ArrayList<String[]> data) {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

        model.setRowCount(0); // clear table

        for (String[] row : data) {
            model.addRow(new Object[]{
                row[0],   // Student ID
                row[1],   // Semester
                row[2],   // CGPA
                row[3],   // Eligibility
                "View"    // Button label
            });
        }
    }
    
    private void showDetails(String studentID, String semester, String eligibility) {
        ArrayList<String[]> grades = loadFile("grades.txt");
        ArrayList<String[]> courses = loadFile("courses.txt");

        ECEView_UI view = new ECEView_UI(studentID, semester, eligibility, grades, courses);
        view.setVisible(true);
    }


    
    
    private void addSidebarHover(javax.swing.JButton btn) {

        Color normal = new Color(95,106,105);        // sidebar color (invisible)
        Color hover  = new Color(130,140,140);       // reveal color
        Color click  = new Color(160,170,170);       // click color

        btn.setBackground(normal);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(hover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(normal);
            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                btn.setBackground(click);
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent e) {
                btn.setBackground(hover);
            }
        });
    }


    public ECE_UI() {
        initComponents();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                int col = jTable1.columnAtPoint(evt.getPoint());
                
                
        if (col == 4) { 
            String sid = jTable1.getValueAt(row, 0).toString();
            String sem = jTable1.getValueAt(row, 1).toString();
            String eligibility = jTable1.getValueAt(row, 3).toString();

            showDetails(sid, sem, eligibility);
        }
            }
        });

        // Set header font
        jTable1.getTableHeader().setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 20));

        // Center header text
        javax.swing.table.DefaultTableCellRenderer headerRenderer = 
                (javax.swing.table.DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        addSidebarHover(jButtonUserManagement);
        addSidebarHover(jButtonEligibility);
        addSidebarHover(jButtonRecovery);
        addSidebarHover(jButtonAPR);
        
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout.setBackground(new java.awt.Color(150,170,170)); // hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout.setBackground(new java.awt.Color(120,140,140)); // normal
            }
        });

    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroud = new javax.swing.JPanel();
        search1 = new javax.swing.JTextField();
        dropdown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search2 = new javax.swing.JButton();
        dashboard = new javax.swing.JPanel();
        jButtonUserManagement = new javax.swing.JButton();
        jButtonEligibility = new javax.swing.JButton();
        jButtonRecovery = new javax.swing.JButton();
        jButtonAPR = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        dashboard1 = new javax.swing.JPanel();
        jButtonUserManagement1 = new javax.swing.JButton();
        jButtonEligibility1 = new javax.swing.JButton();
        jButtonRecovery1 = new javax.swing.JButton();
        jButtonAPR1 = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        ece_sid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eligibility Check and Enrolment");
        setMaximumSize(new java.awt.Dimension(1160, 700));
        setMinimumSize(new java.awt.Dimension(1160, 700));
        setResizable(false);

        backgroud.setBackground(new java.awt.Color(183, 201, 197));
        backgroud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backgroud.setMaximumSize(new java.awt.Dimension(1160, 700));
        backgroud.setMinimumSize(new java.awt.Dimension(1160, 700));
        backgroud.setPreferredSize(new java.awt.Dimension(1160, 700));
        backgroud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        search1.setMaximumSize(new java.awt.Dimension(100, 30));
        search1.setMinimumSize(new java.awt.Dimension(100, 30));
        search1.setPreferredSize(new java.awt.Dimension(100, 30));
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        backgroud.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        dropdown.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Eligible", "No Eligible" }));
        dropdown.setPreferredSize(new java.awt.Dimension(180, 30));
        dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownActionPerformed(evt);
            }
        });
        backgroud.add(dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        jTable1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Semester", "CGPA", "Eligibility", "Details"
            }
        ));
        jTable1.setRowHeight(35);
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        backgroud.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 870, -1));

        search2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        search2.setBorderPainted(false);
        search2.setFocusPainted(false);
        search2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search2.setLabel("Search");
        search2.setPreferredSize(new java.awt.Dimension(70, 30));
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });
        backgroud.add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        dashboard.setBackground(new java.awt.Color(95, 106, 105));

        jButtonUserManagement.setBackground(new java.awt.Color(95, 106, 105));
        jButtonUserManagement.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUserManagement.setText("User Management");
        jButtonUserManagement.setToolTipText("");
        jButtonUserManagement.setBorderPainted(false);
        jButtonUserManagement.setContentAreaFilled(false);
        jButtonUserManagement.setFocusPainted(false);
        jButtonUserManagement.setOpaque(true);
        jButtonUserManagement.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserManagementActionPerformed(evt);
            }
        });

        jButtonEligibility.setBackground(new java.awt.Color(95, 106, 105));
        jButtonEligibility.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonEligibility.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEligibility.setText("<html><center>Eligibility Check<br>and Enrolment</center></html> ");
        jButtonEligibility.setToolTipText("");
        jButtonEligibility.setBorderPainted(false);
        jButtonEligibility.setContentAreaFilled(false);
        jButtonEligibility.setFocusPainted(false);
        jButtonEligibility.setOpaque(true);
        jButtonEligibility.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonEligibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEligibilityActionPerformed(evt);
            }
        });

        jButtonRecovery.setBackground(new java.awt.Color(95, 106, 105));
        jButtonRecovery.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonRecovery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecovery.setText("Course Recovery Plan");
        jButtonRecovery.setToolTipText("");
        jButtonRecovery.setBorderPainted(false);
        jButtonRecovery.setContentAreaFilled(false);
        jButtonRecovery.setFocusPainted(false);
        jButtonRecovery.setOpaque(true);
        jButtonRecovery.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecoveryActionPerformed(evt);
            }
        });

        jButtonAPR.setBackground(new java.awt.Color(95, 106, 105));
        jButtonAPR.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonAPR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAPR.setText("<html><center>Academic<br>Performance Report</center></html> ");
        jButtonAPR.setBorderPainted(false);
        jButtonAPR.setContentAreaFilled(false);
        jButtonAPR.setFocusPainted(false);
        jButtonAPR.setOpaque(true);
        jButtonAPR.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonAPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAPRActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        logout.setText("Log Out");
        logout.setBorderPainted(false);
        logout.setFocusPainted(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEligibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jButtonUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEligibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(62, 62, 62))
        );

        backgroud.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 700));

        title.setBackground(new java.awt.Color(157, 208, 153));
        title.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        title.setText("Eligibility Check and Enrolment");
        title.setToolTipText("");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backgroud.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        dashboard1.setBackground(new java.awt.Color(95, 106, 105));

        jButtonUserManagement1.setBackground(new java.awt.Color(95, 106, 105));
        jButtonUserManagement1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonUserManagement1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUserManagement1.setText("User Management");
        jButtonUserManagement1.setToolTipText("");
        jButtonUserManagement1.setBorderPainted(false);
        jButtonUserManagement1.setContentAreaFilled(false);
        jButtonUserManagement1.setFocusPainted(false);
        jButtonUserManagement1.setOpaque(true);
        jButtonUserManagement1.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonUserManagement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserManagement1ActionPerformed(evt);
            }
        });

        jButtonEligibility1.setBackground(new java.awt.Color(95, 106, 105));
        jButtonEligibility1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonEligibility1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEligibility1.setText("<html><center>Eligibility Check<br>and Enrolment</center></html> ");
        jButtonEligibility1.setToolTipText("");
        jButtonEligibility1.setBorderPainted(false);
        jButtonEligibility1.setContentAreaFilled(false);
        jButtonEligibility1.setFocusPainted(false);
        jButtonEligibility1.setOpaque(true);
        jButtonEligibility1.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonEligibility1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEligibility1ActionPerformed(evt);
            }
        });

        jButtonRecovery1.setBackground(new java.awt.Color(95, 106, 105));
        jButtonRecovery1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonRecovery1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecovery1.setText("Course Recovery Plan");
        jButtonRecovery1.setToolTipText("");
        jButtonRecovery1.setBorderPainted(false);
        jButtonRecovery1.setContentAreaFilled(false);
        jButtonRecovery1.setFocusPainted(false);
        jButtonRecovery1.setOpaque(true);
        jButtonRecovery1.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonRecovery1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecovery1ActionPerformed(evt);
            }
        });

        jButtonAPR1.setBackground(new java.awt.Color(95, 106, 105));
        jButtonAPR1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonAPR1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAPR1.setText("<html><center>Academic<br>Performance Report</center></html> ");
        jButtonAPR1.setBorderPainted(false);
        jButtonAPR1.setContentAreaFilled(false);
        jButtonAPR1.setFocusPainted(false);
        jButtonAPR1.setOpaque(true);
        jButtonAPR1.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonAPR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAPR1ActionPerformed(evt);
            }
        });

        logout1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        logout1.setText("Log Out");
        logout1.setBorderPainted(false);
        logout1.setFocusPainted(false);
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboard1Layout = new javax.swing.GroupLayout(dashboard1);
        dashboard1.setLayout(dashboard1Layout);
        dashboard1Layout.setHorizontalGroup(
            dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard1Layout.createSequentialGroup()
                .addGroup(dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRecovery1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUserManagement1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAPR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEligibility1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dashboard1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(logout1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboard1Layout.setVerticalGroup(
            dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jButtonUserManagement1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEligibility1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRecovery1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAPR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(logout1)
                .addGap(62, 62, 62))
        );

        backgroud.add(dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 700));

        ece_sid.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        ece_sid.setText("Student ID:");
        backgroud.add(ece_sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        search1ActionPerformed(evt);
    }//GEN-LAST:event_search1ActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        String searchID = search1.getText().trim();

        if (searchID.isEmpty() || searchID.equals("Enter Student ID")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a Student ID!");
            return;
        }

        ArrayList<String[]> resultList = loadFile("result.txt");
        ArrayList<String[]> matched = new ArrayList<>();

        for (String[] r : resultList) {
            if (r[0].equalsIgnoreCase(searchID)) {   // Match Student ID
                matched.add(r);
            }
        }

        if (matched.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
        }

        updateTable(matched); 
    }//GEN-LAST:event_search2ActionPerformed

    private void dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownActionPerformed
        String selected = dropdown.getSelectedItem().toString();
        ArrayList<String[]> resultList = loadFile("result.txt");
        ArrayList<String[]> filtered = new ArrayList<>();

        for (String[] r : resultList) {
            if (selected.equals("All")) {
                filtered.add(r);
            } 
            else if (selected.equals("Eligible") && r[3].equalsIgnoreCase("YES")) {
                filtered.add(r);
            } 
            else if (selected.equals("No Eligible") && r[3].equalsIgnoreCase("NO")) {
                filtered.add(r);
            }
        }

        updateTable(filtered);
    }//GEN-LAST:event_dropdownActionPerformed

    private void jButtonUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserManagementActionPerformed

    private void jButtonEligibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEligibilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEligibilityActionPerformed

    private void jButtonRecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecoveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRecoveryActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void jButtonAPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAPRActionPerformed

    private void jButtonUserManagement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserManagement1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserManagement1ActionPerformed

    private void jButtonEligibility1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEligibility1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEligibility1ActionPerformed

    private void jButtonRecovery1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecovery1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRecovery1ActionPerformed

    private void jButtonAPR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAPR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAPR1ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ECE_UI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroud;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dashboard1;
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JLabel ece_sid;
    private javax.swing.JButton jButtonAPR;
    private javax.swing.JButton jButtonAPR1;
    private javax.swing.JButton jButtonEligibility;
    private javax.swing.JButton jButtonEligibility1;
    private javax.swing.JButton jButtonRecovery;
    private javax.swing.JButton jButtonRecovery1;
    private javax.swing.JButton jButtonUserManagement;
    private javax.swing.JButton jButtonUserManagement1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JTextField search1;
    private javax.swing.JButton search2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
