/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_ass;

import java.util.*;
/**
 *
 * @author User
 */
public class ECEView_UI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ECEView_UI.class.getName());

    /**
     * Creates new form ECEView_UI
     */
    public ECEView_UI(String sid, String sem, String eligibility,
                      ArrayList<String[]> grades,
                      ArrayList<String[]> courses) {

        initComponents();
        setLocationRelativeTo(null);
        displayDetails(sid, sem, eligibility, grades, courses);

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close.setBackground(new java.awt.Color(150,170,170));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close.setBackground(new java.awt.Color(120,140,140));
            }
        });
    }
    
        private void displayDetails(String studentID, String semester, String eligibility,
                                ArrayList<String[]> grades, ArrayList<String[]> courses) {

        StringBuilder sb = new StringBuilder();
        double totalGP = 0;
        int totalCH = 0;
        int failCount = 0;

        sb.append("=========== Student: ").append(studentID)
          .append(" (").append(semester).append(") ===========\n\n");

        for (String[] g : grades) {
            if (!g[0].equals(studentID)) continue;
            if (!g[2].equals(semester)) continue;

            String courseID = g[1];
            String grade = g[5];
            double gpa = Double.parseDouble(g[6]);

            String[] c = null;
            for (String[] x : courses) {
                if (x[0].equals(courseID)) c = x;
            }

            int credit = Integer.parseInt(c[2]);
            double gp = gpa * credit;

            totalGP += gp;
            totalCH += credit;
            if (gpa < 2.0) failCount++;

            sb.append(String.format("%-6s | Grade: %-2s (%.2f) × %d credits = %.2f\n",
                    courseID, grade, gpa, credit, gp));
        }

        double cgpa = totalGP / totalCH;

        sb.append("\n-------------------------------------------------------------\n");
        sb.append(String.format("Total Grade Points = %.2f\n", totalGP));
        sb.append("Total Credit Hours = " + totalCH + "\n");
        sb.append("Total Fails = " + failCount + "\n");
        sb.append(String.format("CGPA = %.2f\n", cgpa));
        sb.append("Eligible Next Year: ").append(eligibility).append("\n");
        
         if (eligibility.equalsIgnoreCase("NO")) {
            sb.append("\nReason:\n");

            if (cgpa < 2.0) {
                sb.append("Student does NOT meet the CGPA requirements:\n");
                sb.append("- CGPA below 2.0\n");
            }
            if (failCount > 3) {
                sb.append("Student does NOT meet the fail requirement:\n");
                sb.append("- More than 3 failed courses\n");
            }
            else if (cgpa < 2.0 && failCount > 3) {
                sb.append("Student does NOT meet multiple requirements:\n");
                sb.append("- CGPA below 2.0\n");
                sb.append("- More than 3 failed courses\n");
            }
        }

    text.setText(sb.toString());
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroud = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Result Details");
        setMinimumSize(new java.awt.Dimension(520, 620));
        setResizable(false);

        backgroud.setBackground(new java.awt.Color(182, 201, 197));
        backgroud.setAutoscrolls(true);
        backgroud.setMaximumSize(new java.awt.Dimension(520, 620));
        backgroud.setMinimumSize(new java.awt.Dimension(520, 620));
        backgroud.setPreferredSize(new java.awt.Dimension(520, 620));
        backgroud.setVerifyInputWhenFocusTarget(false);
        backgroud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        title.setText("Result Details");
        backgroud.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(450, 470));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(450, 470));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 470));

        text.setEditable(false);
        text.setColumns(20);
        text.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        text.setLineWrap(true);
        text.setRows(5);
        text.setMaximumSize(new java.awt.Dimension(520, 550));
        text.setMinimumSize(new java.awt.Dimension(520, 550));
        text.setPreferredSize(new java.awt.Dimension(520, 550));
        jScrollPane2.setViewportView(text);

        backgroud.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 440, -1));

        close.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        close.setText("close");
        close.setBorderPainted(false);
        close.setFocusPainted(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        backgroud.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose(); 
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroud;
    private javax.swing.JButton close;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea text;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
