package oodj_ass;

import javax.swing.JOptionPane;

public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());
    private final User currentUser;

    public MainDashboard(User user) {
        initComponents();
        this.currentUser = user;
    
        textField.setText("Welcome, " + user.getUsername() + " (" + user.getRole() + ")");

        btnUserMgmt.setVisible(true);       
        btnECE.setVisible(true);
        btnAPR.setVisible(true);
        btnCRP.setVisible(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textField = new javax.swing.JLabel();
        btnUserMgmt = new javax.swing.JButton();
        btnCRP = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnECE = new javax.swing.JButton();
        btnAPR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textField.setText("Dashboard");

        btnUserMgmt.setText("User Management");
        btnUserMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserMgmtActionPerformed(evt);
            }
        });

        btnCRP.setText("Course Recovery");
        btnCRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRPActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnECE.setText("Eligibity Check");
        btnECE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnECEActionPerformed(evt);
            }
        });

        btnAPR.setText("Academic Reporting");
        btnAPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUserMgmt)
                            .addComponent(btnCRP)
                            .addComponent(btnLogout)
                            .addComponent(btnECE)
                            .addComponent(btnAPR))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(textField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnUserMgmt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnECE)
                .addGap(18, 18, 18)
                .addComponent(btnAPR)
                .addGap(28, 28, 28)
                .addComponent(btnCRP)
                .addGap(41, 41, 41)
                .addComponent(btnLogout)
                .addGap(30, 30, 30))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMgmtActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserMgmtActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Logger.writeLog(currentUser.getUsername(), "LOGOUT");
        new LoginUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRPActionPerformed
        // TODO add your handling code here:
        if (currentUser.getRole().equalsIgnoreCase("ADMIN")) {
            JOptionPane.showMessageDialog(this, 
                "ACCESS DENIED: Course Recovery is for Academic Officers only.", 
                "Restricted Access", 
                JOptionPane.WARNING_MESSAGE);
            return; 
        }

        JOptionPane.showMessageDialog(this, "Opening Course Recovery Plan...");
    }//GEN-LAST:event_btnCRPActionPerformed

    private void btnECEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnECEActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Opening Eligibility Check and Enrolment...");
    }//GEN-LAST:event_btnECEActionPerformed

    private void btnAPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPRActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Opening Academic Performance Reports...");
    }//GEN-LAST:event_btnAPRActionPerformed


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAPR;
    private javax.swing.JButton btnCRP;
    private javax.swing.JButton btnECE;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUserMgmt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel textField;
    // End of variables declaration//GEN-END:variables
}
