package oodj_ass;

import javax.swing.JOptionPane;

public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());
    private final User currentUser;

    
    public MainDashboard(User user) {
        initComponents();
        this.currentUser = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelWelcomeMessg = new javax.swing.JLabel();
        labelWelcomeMessg1 = new javax.swing.JLabel();
        labelWelcomeMessg2 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        jButtonUserManagement = new javax.swing.JButton();
        jButtonEligibility = new javax.swing.JButton();
        jButtonRecovery = new javax.swing.JButton();
        jButtonAPR = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 700));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(183, 201, 197));
        jPanel4.setPreferredSize(new java.awt.Dimension(1160, 700));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelWelcomeMessg.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        labelWelcomeMessg.setText("TO");
        jPanel4.add(labelWelcomeMessg, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 277, -1, -1));

        labelWelcomeMessg1.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        labelWelcomeMessg1.setText("COURSE RECOVERY SYSTEM");
        jPanel4.add(labelWelcomeMessg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 339, -1, -1));

        labelWelcomeMessg2.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        labelWelcomeMessg2.setText("WELCOME");
        jPanel4.add(labelWelcomeMessg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        dashboard.setBackground(new java.awt.Color(95, 106, 105));
        dashboard.setPreferredSize(new java.awt.Dimension(210, 700));

        jButtonUserManagement.setBackground(new java.awt.Color(95, 106, 105));
        jButtonUserManagement.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUserManagement.setText("User Management");
        jButtonUserManagement.setToolTipText("");
        jButtonUserManagement.setBorderPainted(false);
        jButtonUserManagement.setContentAreaFilled(false);
        jButtonUserManagement.setFocusPainted(false);
        jButtonUserManagement.setOpaque(true);
        jButtonUserManagement.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserManagementActionPerformed(evt);
            }
        });

        jButtonEligibility.setBackground(new java.awt.Color(95, 106, 105));
        jButtonEligibility.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonEligibility.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEligibility.setText("<html><center>Eligibility Check<br>and Enrolment</center></html> ");
        jButtonEligibility.setToolTipText("");
        jButtonEligibility.setBorderPainted(false);
        jButtonEligibility.setContentAreaFilled(false);
        jButtonEligibility.setFocusPainted(false);
        jButtonEligibility.setOpaque(true);
        jButtonEligibility.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonEligibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEligibilityActionPerformed(evt);
            }
        });

        jButtonRecovery.setBackground(new java.awt.Color(95, 106, 105));
        jButtonRecovery.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonRecovery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecovery.setText("Course Recovery Plan");
        jButtonRecovery.setToolTipText("");
        jButtonRecovery.setBorderPainted(false);
        jButtonRecovery.setContentAreaFilled(false);
        jButtonRecovery.setFocusPainted(false);
        jButtonRecovery.setOpaque(true);
        jButtonRecovery.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecoveryActionPerformed(evt);
            }
        });

        jButtonAPR.setBackground(new java.awt.Color(95, 106, 105));
        jButtonAPR.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButtonAPR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAPR.setText("<html><center>Academic<br>Performance Report</center></html> ");
        jButtonAPR.setBorderPainted(false);
        jButtonAPR.setContentAreaFilled(false);
        jButtonAPR.setFocusPainted(false);
        jButtonAPR.setOpaque(true);
        jButtonAPR.setPreferredSize(new java.awt.Dimension(210, 70));
        jButtonAPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAPRActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        logout.setText("Log Out");
        logout.setBorderPainted(false);
        logout.setFocusPainted(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(95, 106, 105));
        btnHome.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnHome.setText("HOME");
        btnHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEligibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(logout))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(jButtonUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEligibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(62, 62, 62))
        );

        jPanel1.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        new MainDashboard(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jButtonUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserManagementActionPerformed
        new AdminDashboard(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonUserManagementActionPerformed

    private void jButtonEligibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEligibilityActionPerformed
        new ECE_UI(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEligibilityActionPerformed

    private void jButtonRecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecoveryActionPerformed
       if (currentUser.getRole().equalsIgnoreCase("ADMIN")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Access Denied: Administrators are not allowed to access the Course Recovery Plan.", 
                "Restricted Access", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            new CRP_UI(currentUser).setVisible(true);
            this.dispose();
       }
    }//GEN-LAST:event_jButtonRecoveryActionPerformed

    private void jButtonAPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAPRActionPerformed
        new APR_UI(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAPRActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Logger.writeLog(currentUser.getUsername(), "LOGOUT");
        new LoginUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JPanel dashboard;
    private javax.swing.JButton jButtonAPR;
    private javax.swing.JButton jButtonEligibility;
    private javax.swing.JButton jButtonRecovery;
    private javax.swing.JButton jButtonUserManagement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelWelcomeMessg;
    private javax.swing.JLabel labelWelcomeMessg1;
    private javax.swing.JLabel labelWelcomeMessg2;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
