package oodj_ass;

import javax.swing.JOptionPane;

public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());
    private final User currentUser;

    public MainDashboard(User user) {
        initComponents();
        this.currentUser = user;
    
        textField.setText("Welcome, " + user.getUsername() + " (" + user.getRole() + ")");

        btnUserMgmt.setVisible(true);       
        btnECE.setVisible(true);
        btnAPR.setVisible(true);
        btnCRP.setVisible(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnECE = new javax.swing.JButton();
        btnUserMgmt = new javax.swing.JButton();
        btnAPR = new javax.swing.JButton();
        btnCRP = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        textField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1160, 700));
        setMinimumSize(new java.awt.Dimension(1160, 700));
        setPreferredSize(new java.awt.Dimension(1160, 700));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(210, 700));
        jPanel2.setMinimumSize(new java.awt.Dimension(210, 700));
        jPanel2.setPreferredSize(new java.awt.Dimension(210, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnECE.setBackground(new java.awt.Color(0, 0, 0));
        btnECE.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnECE.setForeground(new java.awt.Color(255, 255, 255));
        btnECE.setText("Eligibity Check");
        btnECE.setMaximumSize(new java.awt.Dimension(172, 31));
        btnECE.setMinimumSize(new java.awt.Dimension(172, 31));
        btnECE.setPreferredSize(new java.awt.Dimension(172, 31));
        btnECE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnECEActionPerformed(evt);
            }
        });
        jPanel2.add(btnECE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 40));

        btnUserMgmt.setBackground(new java.awt.Color(0, 0, 0));
        btnUserMgmt.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnUserMgmt.setForeground(new java.awt.Color(255, 255, 255));
        btnUserMgmt.setText("User Management");
        btnUserMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserMgmtActionPerformed(evt);
            }
        });
        jPanel2.add(btnUserMgmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, 40));

        btnAPR.setBackground(new java.awt.Color(0, 0, 0));
        btnAPR.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnAPR.setForeground(new java.awt.Color(255, 255, 255));
        btnAPR.setText("Academic Reporting");
        btnAPR.setMaximumSize(new java.awt.Dimension(172, 31));
        btnAPR.setMinimumSize(new java.awt.Dimension(172, 31));
        btnAPR.setPreferredSize(new java.awt.Dimension(172, 31));
        btnAPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPRActionPerformed(evt);
            }
        });
        jPanel2.add(btnAPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 210, 40));

        btnCRP.setBackground(new java.awt.Color(0, 0, 0));
        btnCRP.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnCRP.setForeground(new java.awt.Color(255, 255, 255));
        btnCRP.setText("Course Recovery");
        btnCRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRPActionPerformed(evt);
            }
        });
        jPanel2.add(btnCRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 210, 40));

        btnLogout.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 210, 50));

        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 880));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(113, 149, 115));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel1)
                .addContainerGap(631, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(130, 196, 156));

        textField.setBackground(new java.awt.Color(130, 196, 156));
        textField.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(712, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 1020, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPRActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Opening Academic Performance Reports...");
    }//GEN-LAST:event_btnAPRActionPerformed

    private void btnECEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnECEActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Opening Eligibility Check and Enrolment...");
    }//GEN-LAST:event_btnECEActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Logger.writeLog(currentUser.getUsername(), "LOGOUT");
        new LoginUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRPActionPerformed
        // TODO add your handling code here:
        if (currentUser.getRole().equalsIgnoreCase("ADMIN")) {
            JOptionPane.showMessageDialog(this,
                "ACCESS DENIED: Course Recovery is for Academic Officers only.",
                "Restricted Access",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Opening Course Recovery Plan...");
    }//GEN-LAST:event_btnCRPActionPerformed

    private void btnUserMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMgmtActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserMgmtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldActionPerformed


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAPR;
    private javax.swing.JButton btnCRP;
    private javax.swing.JButton btnECE;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUserMgmt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
